[phases.setup]
nixPkgs = ['nodejs-16_x', 'yarn-1_x', 'openssl']

[phases.install]
cmd = 'yarn install --frozen-lockfile'

[phases.build]
cmd = 'yarn run build'

[phases.deploy]
cmd = 'yarn run build'
numReplicas = 1
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"
